wandb_version: 1

experiment_name:
  desc: null
  value: inter-layer-13
gpu:
  desc: null
  value: true
trainer_num_epochs:
  desc: null
  value: 5000
probe_num_layers:
  desc: null
  value: 1
activation:
  desc: null
  value: sigmoid
probe_num_hidden_units:
  desc: null
  value: 50
result_path:
  desc: null
  value: ./results
temperature:
  desc: null
  value: 1.0
temp_annealing:
  desc: null
  value: false
temp_min:
  desc: null
  value: 0.5
anneal_rate:
  desc: null
  value: 3.0e-05
patience:
  desc: null
  value: 50
l1_weight:
  desc: null
  value: 0.0
l2_weight:
  desc: null
  value: 0.0
mc_samples:
  desc: null
  value: 5
batch_size:
  desc: null
  value: null
learning_rate:
  desc: null
  value: 0.01
entropy_scale:
  desc: null
  value: 0.01
decomposable:
  desc: null
  value: false
wandb:
  desc: null
  value: true
wandb_tag:
  desc: null
  value: null
language:
  desc: null
  value:
  - UD_Tamil
attribute:
  desc: null
  value: Gender
trainer:
  desc: null
  value: poisson
embedding:
  desc: null
  value: bloom-1b1-intermediate-global_step400000
selection_size:
  desc: null
  value: 50
selection_criterion:
  desc: null
  value: mi
_wandb:
  desc: null
  value:
    python_version: 3.8.11
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1687710519.469845
    t:
      1:
      - 1
      - 55
      3:
      - 15
      - 16
      - 23
      4: 3.8.11
      5: 0.15.3
      8:
      - 5
