wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.16
    start_time: 1687786599.623984
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 15
      - 16
      - 17
      - 23
      - 37
      4: 3.8.16
      5: 0.13.11
      8:
      - 5
      10:
      - 3
activation:
  desc: null
  value: sigmoid
anneal_rate:
  desc: null
  value: 3.0e-05
attribute:
  desc: null
  value: Number
batch_size:
  desc: null
  value: null
decomposable:
  desc: null
  value: false
embedding:
  desc: null
  value: bloom-1b1-intermediate-global_step400000
entropy_scale:
  desc: null
  value: 0.01
experiment_name:
  desc: null
  value: inter-layer-17
gpu:
  desc: null
  value: true
l1_weight:
  desc: null
  value: 0.0
l2_weight:
  desc: null
  value: 0.0
language:
  desc: null
  value:
  - UD_Tamil
learning_rate:
  desc: null
  value: 0.005
mc_samples:
  desc: null
  value: 5
patience:
  desc: null
  value: 50
probe_num_hidden_units:
  desc: null
  value: 50
probe_num_layers:
  desc: null
  value: 1
result_path:
  desc: null
  value: ./results
selection_criterion:
  desc: null
  value: mi
selection_size:
  desc: null
  value: 50
temp_annealing:
  desc: null
  value: false
temp_min:
  desc: null
  value: 0.5
temperature:
  desc: null
  value: 1.0
trainer:
  desc: null
  value: poisson
trainer_num_epochs:
  desc: null
  value: 5000
wandb:
  desc: null
  value: true
wandb_offline:
  desc: null
  value: false
wandb_tag:
  desc: null
  value: null
